---
title: "pinetree protein plots"
author: "Alex Lukasiewicz"
date: "12/11/2018"
output: html_document
---

To generate an array of codon rates to screen for drastic changes in stable state

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(cowplot)
```


```{r}
pinetree_counts <- read.table("data/codon_optimization_data/test_protein_counts.tsv", sep = "\t", header = TRUE)
pinetree_tbl <- as.tibble(pinetree_counts)
pinetree_plot <- pinetree_tbl %>% filter(species %in% c("proteinP","__ribosome")) 
gene_plot <- ggplot(data = pinetree_plot, aes(x=time, y=protein, group=species)) + geom_line(aes(color = species)) + labs(title = 'Protein production and free ribosomes in simulation', x = 'time',  y = 'counts') + scale_color_viridis_d() + theme_bw()
plot(gene_plot)
save_plot("half_slow_example.png", gene_plot, base_aspect_ratio = 1.3)
```
The production rate for a transcript with 54% slow and 46% fast codons was 0.68 protein/s
```{r}
pinetree_counts <- read.table("data/codon_optimization_data/slow_transcript_2_counts.tsv", sep = "\t", header = TRUE)
pinetree_tbl <- as.tibble(pinetree_counts)
pinetree_plot <- pinetree_tbl %>% filter(species %in% c("proteinP","__ribosome")) 
ggplot(data = pinetree_plot, aes(x=time, y=protein, group=species)) + geom_line(aes(color = species)) + ggtitle("Protein Production Rate with slow codons")
```
The protein production rate for a transcript with all slow codons was 0.67 protein/s
```{r}
pinetree_counts <- read.table("data/codon_optimization_data/fast_transcript_3_counts.tsv", sep = "\t", header = TRUE)
pinetree_tbl <- as.tibble(pinetree_counts)
pinetree_plot <- pinetree_tbl %>% filter(species %in% c("proteinP","__ribosome")) 
ggplot(data = pinetree_plot, aes(x=time, y=protein, group=species)) + geom_line(aes(color = species)) + ggtitle("Protein Production Rate with fast codons")
```
The system attained steady state after 24 seconds and began producing proteins at a rate of 0.87 proteins/s

```{r}
pinetree_counts <- read.table("data/codon_optimization_data/function_test_counts.tsv", sep = "\t", header = TRUE)
pinetree_tbl <- as.tibble(pinetree_counts)
pinetree_plot <- pinetree_tbl %>% filter(species %in% c("proteinP","__ribosome")) 
ggplot(data = pinetree_plot, aes(x=time, y=protein, group=species)) + geom_line(aes(color = species)) + ggtitle("mixed transcript")
```
